version: "3.8"
services:
  db:
    image: "postgres:12"
    container_name: mhinc-postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data:Z
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST:-localhost}
      - POSTGRES_DB=${POSTGRES_DB:-mhinc}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres_password}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
    healthcheck:
      test: pg_isready -U postgres -d postgres
      interval: 5s
      timeout: 3s
      retries: 3

  api:
    build:
      context: .
      dockerfile: ./dockerfile.api
    container_name: mhinc-api
    ports:
      - "3008:3008"

    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    env_file:
      - ./.env.local
    environment:
      - DATABASE_CONNECTION_STRING=postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres_password}@${POSTGRES_HOST:-db}:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-mhinc}

volumes:
  pgdata:
